apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: task-hpa
  namespace: tasks-prod
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: openshift-tasks
  targetCPUUtilizationPercentage: 80